serviceAccount: $SERVICE_ACCOUNT
options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - extract
  - --region=europe-west1
  - --source=.
  - --trigger-http
  - --runtime=python310
  - --entry-point=main
  - --set-env-vars=API_URL=https://newsapi.org/v2/everything?q=apple,PROJECT_ID=apple-news-db6d6,FIRESTORE_COLLECTION=apple-news-raw,FIRESTORE_DB=apple-news-2025
#  env:
#  - 'API_URL=https://newsapi.org/v2/everything?q=apple'
#  - 'LOG_PATH=../apple-news-extract/logs/'
#  - 'PROJECT_ID=apple-news-db6d6'

